### ISSUE TITLE
Missed to account beginning of table, but accounts end of table with 0 executions

### ISSUE THREAD

**Issue by urzds** [keplerproject/luacov#40]
In the following code, LuaCov does not account the first line of the table (which is surely executed), but accounts the closing parenthesis with 0 executions, even though it does not contain any statements:
```luacov
   2            local req = http.request({
                        method = "GET",
   1                    hostname = hostname,
   1                    port = port,
   1                    path = path,
***0            },
                function(res)
<...>
                end)
```

**Comment by mpeterv** [comment]
Assuming you are using LuaJIT, the first line of the table is missed because LuaJIT does not actually perform an assignment there. It caches constant parts of tables and duplicates them when needed, and sets only pairs with non-constant keys or values, such as the other three pairs in this case.

The closing parenthesis issue is a false positive, I'll see if line filtering can be improved there.

**Comment by mpeterv** [comment]
False positive fixed on master branch.

**Comment by urzds** [comment]
Thanks! The fix works.
